#!/bin/bash

sudo apt-get update
sudo apt-get -y install python-wstool python-rospkg python-rosinstall python-vcstools python-rosdep
sudo apt-get -y install ros-groovy-ros ros-groovy-catkin
rm -rf ${WORKSPACE}/ecl
mkdir -p ${WORKSPACE}/ecl/src
mkdir -p ${WORKSPACE}/ecl/build/debug
mkdir -p ${WORKSPACE}/ecl/build/release
mkdir -p ${WORKSPACE}/ecl/install/debug
mkdir -p ${WORKSPACE}/ecl/install/release
wstool init -j3 ${WORKSPACE}/ecl/src https://raw.github.com/stonier/ecl_tools/master/rosinstall/ecl_groovy.rosinstall
echo "========== Setting up Ros Environment =========="
source /opt/ros/groovy/setup.bash
catkin_init_workspace ${WORKSPACE}/ecl/src
echo "========== Compiling =========="
catkin_make --no-color --directory=${WORKSPACE}/ecl/build --source=${WORKSPACE}/ecl/src --build=debug -DCMAKE_INSTALL_PREFIX="${WORKSPACE}/ecl/install/debug"
cd ${WORKSPACE}/ecl/build/debug
make install
catkin_make --no-color --directory=${WORKSPACE}/ecl/build --source=${WORKSPACE}/ecl/src --build=release -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="${WORKSPACE}/ecl/install/release"
cd ${WORKSPACE}/ecl/build/release
make install
